kind: Service
apiVersion: v1
metadata:
  name: logdemo
spec:
  type: NodePort
  selector:
    app: logdemo
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: logdemo
spec:
  backend:
    serviceName: logdemo
    servicePort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logdemo
  labels:
    app: logdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logdemo
  template:
    metadata:
      labels:
        app: logdemo
    spec:
      containers:
      - name: logdemo
        image: gcr.io/bigquery-tools/logdemo@sha256:297e0d75aed67653b9c520a5c1bb99c16d769d665fe158a32e5c4b031c7f619e
        ports:
        - containerPort: 8080
